#!/bin/bash

set -e

CONTRIB="$(dirname "$(readlink -e "$0")")"
ROOT_FOLDER="$CONTRIB"/..
PACKAGES="$ROOT_FOLDER"/packages/
LOCALE="$ROOT_FOLDER"/electrum/locale/

if [ ! -d "$LOCALE" ]; then
  echo "Run pull_locale first!"
  exit 1
fi

if [ ! -d "$PACKAGES" ]; then
  echo "Run make_packages first!"
  exit 1
fi

pushd ./electrum/gui/kivy/

make theming

export P4A_RELEASE_KEYSTORE=/home/user/wspace/electrum-cpu/contrib/apk_signing.jks
export P4A_RELEASE_KEYSTORE_PASSWD=$APK_PASSWORD
export P4A_RELEASE_KEYALIAS_PASSWD=$APK_PASSWORD
export P4A_RELEASE_KEYALIAS=key0
make release

popd
