sudo: true
dist: xenial
language: python
python:
    - 3.6
    - 3.7
git:
  depth: false
addons:
  apt:
    sources:
      - sourceline: 'ppa:tah83/secp256k1'
    packages:
      - libsecp256k1-0
before_install:
  - git tag
install:
  - pip install -r contrib/requirements/requirements-travis.txt
cache:
  - pip: true
  - directories:
    - /tmp/electrum-cpu-build
script:
    - tox
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install requests && contrib/push_locale; fi
    - coveralls
jobs:
  include:
    - stage: binary builds
      name: "Windows build"
      sudo: true
      language: c
      python: false
      env:
        - TARGET_OS=Windows
      services:
        - docker
      install:
        - sudo docker build --no-cache -t electrum-wine-builder-img ./contrib/build-wine/
      script:
        - sudo docker run --name electrum-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum-cpu --rm --workdir /opt/wine64/drive_c/electrum-cpu/contrib/build-wine electrum-wine-builder-img ./build.sh
      after_success: true
      deploy:
        provider: releases
        api_key:
          secure: ZbBHUF9kE3bqn89fFJ/nV+H0IIpYaKEOsa+N1UJOXB3mRkMZ1dWDXrQ4TENEKLmoNocY9h5Xt3Zz+047gdk3LrTqKUvB8poCFkphSLU1DoNe6IkyAIpnLz4KOYRDDb5UQIZ6T2ZggaEaYOWs1tQjZDi9rtdaFDS5tIXGPTjstgZfKoOV9vGQg4Whk2yEucI+KqEevyh11BRsR9b1XYU9xeavON2ByJ72K4tdTO2nGkgdQ9xgvu74q55at42E6pLJxk9McUIsd+Nst51Na5aQ6YcJER8fE69NXc68wKZLV2oihWmbNX8gMYcgERFIDkvsCajv78A4O4+etb2YGZIJD02b69cs1lBMHLJed6uqOWGsjVQd5oyG9KgA6t1Us0E6MyJFa068Jp9ZbM4kQQQ6prBHtP3FwiOLE7AwsXjA/B+F2HFMx78LSi5Dn+QT4ZVapmHXbxxdJoSAaZoVs9YRHcM0OmC7QaLhrKSDRP/1ru7f+PweieuDShYCITDmemMOKH1IWv8RFrV8UL8DJsV1LjcrTPS+OUk1HpTeYdHLbLxYqULWueHGcKpLo9rZ2hc3oY5g0ysdO36GIhFiXJl4j/xT36k1iSX41RN2TEekrSeuFofILLUHXYtESYtJOticzASWXnOKdFre7K4Mri7PEkE932ovzdBXWZ8guakmPiA=
        file:
          - contrib/build-wine/dist/electrum-cpu-$TRAVIS_TAG-portable.exe
          - contrib/build-wine/dist/electrum-cpu-$TRAVIS_TAG-setup.exe
        file_glob: true
        draft: true
        on:
          repo: cpuchain/electrum-cpu
          tags: true
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
    - name: "Android build"
      dist: xenial
      language: python
      python: 3.7
      services:
        - docker
      install:
        - openssl aes-256-cbc -K $encrypted_e2b2fe01fb2a_key -iv $encrypted_e2b2fe01fb2a_iv -in contrib/apk_signing.jks.enc -out contrib/apk_signing.jks -d
        - pip install requests && ./contrib/pull_locale
        - ./contrib/make_packages
        - sudo docker build --no-cache -t electrum-android-builder-img electrum/gui/kivy/tools
      script:
        - sudo chown -R 1000:1000 .
        # Output something every minute or Travis kills the job
        - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - sudo docker run -it -u 1000:1000 --rm --name electrum-android-builder-cont -v $PWD:/home/user/wspace/electrum-cpu --workdir /home/user/wspace/electrum-cpu -e APK_PASSWORD=$APK_PASSWORD electrum-android-builder-img ./contrib/make_apk_travis
        # kill background sleep loop
        - kill %1
        - ls -la bin
        - if [ $(ls bin | grep -c ElectrumCPU-*) -eq 0 ]; then exit 1; fi
      after_success: true
      before_deploy: sudo chown -R travis:travis /home/travis/
      deploy:
        provider: releases
        api_key:
          secure: ZbBHUF9kE3bqn89fFJ/nV+H0IIpYaKEOsa+N1UJOXB3mRkMZ1dWDXrQ4TENEKLmoNocY9h5Xt3Zz+047gdk3LrTqKUvB8poCFkphSLU1DoNe6IkyAIpnLz4KOYRDDb5UQIZ6T2ZggaEaYOWs1tQjZDi9rtdaFDS5tIXGPTjstgZfKoOV9vGQg4Whk2yEucI+KqEevyh11BRsR9b1XYU9xeavON2ByJ72K4tdTO2nGkgdQ9xgvu74q55at42E6pLJxk9McUIsd+Nst51Na5aQ6YcJER8fE69NXc68wKZLV2oihWmbNX8gMYcgERFIDkvsCajv78A4O4+etb2YGZIJD02b69cs1lBMHLJed6uqOWGsjVQd5oyG9KgA6t1Us0E6MyJFa068Jp9ZbM4kQQQ6prBHtP3FwiOLE7AwsXjA/B+F2HFMx78LSi5Dn+QT4ZVapmHXbxxdJoSAaZoVs9YRHcM0OmC7QaLhrKSDRP/1ru7f+PweieuDShYCITDmemMOKH1IWv8RFrV8UL8DJsV1LjcrTPS+OUk1HpTeYdHLbLxYqULWueHGcKpLo9rZ2hc3oY5g0ysdO36GIhFiXJl4j/xT36k1iSX41RN2TEekrSeuFofILLUHXYtESYtJOticzASWXnOKdFre7K4Mri7PEkE932ovzdBXWZ8guakmPiA=
        file:
          - bin/ElectrumCPU-$TRAVIS_TAG.0-release.apk
        file_glob: true
        draft: true
        on:
          repo: cpuchain/electrum-cpu
          tags: true
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
    - name: "MacOS build"
      os: osx
      language: c
      env:
        - TARGET_OS=macOS
      python: false
      install:
        - git fetch --all --tags
      script: ./contrib/osx/make_osx
      after_script: ls -lah dist && md5 dist/*
      after_success: true
      deploy:
        provider: releases
        api_key:
          secure: ZbBHUF9kE3bqn89fFJ/nV+H0IIpYaKEOsa+N1UJOXB3mRkMZ1dWDXrQ4TENEKLmoNocY9h5Xt3Zz+047gdk3LrTqKUvB8poCFkphSLU1DoNe6IkyAIpnLz4KOYRDDb5UQIZ6T2ZggaEaYOWs1tQjZDi9rtdaFDS5tIXGPTjstgZfKoOV9vGQg4Whk2yEucI+KqEevyh11BRsR9b1XYU9xeavON2ByJ72K4tdTO2nGkgdQ9xgvu74q55at42E6pLJxk9McUIsd+Nst51Na5aQ6YcJER8fE69NXc68wKZLV2oihWmbNX8gMYcgERFIDkvsCajv78A4O4+etb2YGZIJD02b69cs1lBMHLJed6uqOWGsjVQd5oyG9KgA6t1Us0E6MyJFa068Jp9ZbM4kQQQ6prBHtP3FwiOLE7AwsXjA/B+F2HFMx78LSi5Dn+QT4ZVapmHXbxxdJoSAaZoVs9YRHcM0OmC7QaLhrKSDRP/1ru7f+PweieuDShYCITDmemMOKH1IWv8RFrV8UL8DJsV1LjcrTPS+OUk1HpTeYdHLbLxYqULWueHGcKpLo9rZ2hc3oY5g0ysdO36GIhFiXJl4j/xT36k1iSX41RN2TEekrSeuFofILLUHXYtESYtJOticzASWXnOKdFre7K4Mri7PEkE932ovzdBXWZ8guakmPiA=
        file:
          - dist/electrum-cpu-$TRAVIS_TAG.dmg
        file_glob: true
        draft: true
        on:
          repo: cpuchain/electrum-cpu
          tags: true
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
    - name: "AppImage build"
      sudo: true
      language: c
      python: false
      services:
        - docker
      install:
        - sudo docker build --no-cache -t electrum-appimage-builder-img ./contrib/build-linux/appimage/
      script:
        - sudo docker run --name electrum-appimage-builder-cont -v $PWD:/opt/electrum-cpu --rm --workdir /opt/electrum-cpu/contrib/build-linux/appimage electrum-appimage-builder-img ./build.sh
      after_success: true
      deploy:
        provider: releases
        api_key:
          secure: ZbBHUF9kE3bqn89fFJ/nV+H0IIpYaKEOsa+N1UJOXB3mRkMZ1dWDXrQ4TENEKLmoNocY9h5Xt3Zz+047gdk3LrTqKUvB8poCFkphSLU1DoNe6IkyAIpnLz4KOYRDDb5UQIZ6T2ZggaEaYOWs1tQjZDi9rtdaFDS5tIXGPTjstgZfKoOV9vGQg4Whk2yEucI+KqEevyh11BRsR9b1XYU9xeavON2ByJ72K4tdTO2nGkgdQ9xgvu74q55at42E6pLJxk9McUIsd+Nst51Na5aQ6YcJER8fE69NXc68wKZLV2oihWmbNX8gMYcgERFIDkvsCajv78A4O4+etb2YGZIJD02b69cs1lBMHLJed6uqOWGsjVQd5oyG9KgA6t1Us0E6MyJFa068Jp9ZbM4kQQQ6prBHtP3FwiOLE7AwsXjA/B+F2HFMx78LSi5Dn+QT4ZVapmHXbxxdJoSAaZoVs9YRHcM0OmC7QaLhrKSDRP/1ru7f+PweieuDShYCITDmemMOKH1IWv8RFrV8UL8DJsV1LjcrTPS+OUk1HpTeYdHLbLxYqULWueHGcKpLo9rZ2hc3oY5g0ysdO36GIhFiXJl4j/xT36k1iSX41RN2TEekrSeuFofILLUHXYtESYtJOticzASWXnOKdFre7K4Mri7PEkE932ovzdBXWZ8guakmPiA=
        file:
          - dist/electrum-cpu-$TRAVIS_TAG-x86_64.AppImage
        file_glob: true
        draft: true
        on:
          repo: cpuchain/electrum-cpu
          tags: true
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
    - name: "Tarball build"
      dist: xenial
      language: python
      python: 3.7
      install:
        - pip install requests && ./contrib/pull_locale
        - ./contrib/make_packages
      script:
        - ./contrib/make_tgz
      after_success: true
      deploy:
        provider: releases
        api_key:
          secure: ZbBHUF9kE3bqn89fFJ/nV+H0IIpYaKEOsa+N1UJOXB3mRkMZ1dWDXrQ4TENEKLmoNocY9h5Xt3Zz+047gdk3LrTqKUvB8poCFkphSLU1DoNe6IkyAIpnLz4KOYRDDb5UQIZ6T2ZggaEaYOWs1tQjZDi9rtdaFDS5tIXGPTjstgZfKoOV9vGQg4Whk2yEucI+KqEevyh11BRsR9b1XYU9xeavON2ByJ72K4tdTO2nGkgdQ9xgvu74q55at42E6pLJxk9McUIsd+Nst51Na5aQ6YcJER8fE69NXc68wKZLV2oihWmbNX8gMYcgERFIDkvsCajv78A4O4+etb2YGZIJD02b69cs1lBMHLJed6uqOWGsjVQd5oyG9KgA6t1Us0E6MyJFa068Jp9ZbM4kQQQ6prBHtP3FwiOLE7AwsXjA/B+F2HFMx78LSi5Dn+QT4ZVapmHXbxxdJoSAaZoVs9YRHcM0OmC7QaLhrKSDRP/1ru7f+PweieuDShYCITDmemMOKH1IWv8RFrV8UL8DJsV1LjcrTPS+OUk1HpTeYdHLbLxYqULWueHGcKpLo9rZ2hc3oY5g0ysdO36GIhFiXJl4j/xT36k1iSX41RN2TEekrSeuFofILLUHXYtESYtJOticzASWXnOKdFre7K4Mri7PEkE932ovzdBXWZ8guakmPiA=
        file:
          - dist/Electrum-CPU-$TRAVIS_TAG.tar.gz
        file_glob: true
        draft: true
        on:
          repo: cpuchain/electrum-cpu
          tags: true
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
    - stage: release check
      install:
          - git fetch --all --tags
      script:
        - ./contrib/deterministic-build/check_submodules.sh
      after_success: true
      if: tag IS present
